version: '3.5'
services:
  i2b2:
    image: medco/i2b2:v1.7.10.0001-MedCo:dev
    build:
      context: .
      target: release
    environment:
    - I2B2_DB_HOST=postgresql
    - I2B2_DB_PORT=5432
    - I2B2_DB_USER=i2b2
    - I2B2_DB_PW=i2b2
    - I2B2_DB_NAME=i2b2demo
    - WILDFLY_ADMIN_PASSWORD=admin
    - I2B2_DOMAIN_NAME=i2b2demo
    - I2B2_SERVICE_PASSWORD=pFjy3EjDVwLfT2rB9xkK
    - DEFAULT_USER_PASSWORD=demouser
    - AXIS2_LOGLEVEL=INFO
